### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by rsarov** [rupor-github/InpxCreator#10]
Привет у вас же был нормальный Readme по использованию программы?
Дело в том что у меня есть своя раздача и мне частенько задают вопросы как то как се
Я их отсылаю сюда типа если надо что то не стандартное то бери и делай сам, а мне отвечают
linux танцы с барабанами не разумеем.
А сегодня посмотрел readme правда не понять ничего с ходу.
Или вам этого не надо, ну чтобы пришел человек как то  мог разобраться как пользоваться?

**Comment by rupor-github** [comment]
Нормальный readme был году так примерно в 2009. С тех пор программа здорово поменялась - а поддерживать его в updated состоянии у меня нет времени. Поэтому он был заменен на [сокращенный вариант](https://github.com/rupor-github/InpxCreator/tree/master/misc). 

Причем здесь linux я не понимаю, примеры скриптов есть и для Windows. Все программы печатают развернутый usage.

Мне вообще ничего не надо, как не надо чтобы пришел человек и с хогу разобрался - эта программа писалась для себя и довольно узкого круга пользователей (производивших каталогизаторы), причем очень давно. Идея о том, что индивидуальные пользователи будут этим заниматься может и хороша -
 но не для меня, так как я поддерживать большое количество достаточно неподготовленных людей не могу. Тем не менее ошибки я чиню, на вопросы отвечаю и даже добавляю новые features - в чем вы могли убедиться.

Если кто-нибудь захочет поучаствовать в проекте и написать документацию - я могу открыть здесь WiKi на проекте.

**Comment by rsarov** [comment]
хозяин - барин
