### ISSUE TITLE
Query error in lib2inpx

### ISSUE THREAD

**Issue by alexeystalker** [rupor-github/InpxCreator#11]
Добрый день!
Пытаюсь собрать inpx файл из дампа Флибусты. Powershell скриптом из последнего релиза выкачиваю sql файлы, затем вызываю lib2inpx.exe:
` lib2inpx.exe --verbose --quick-fix --clean-aliases --db-format 2017-05-31 --inpx inpx\flibusta.inpx --clean-when-done %папка с sql файлами%`
Получаю ошибку:
`***ERROR: Query error (1054) Unknown column 'bid' in 'field list'
SELECT MAX(`bid`) FROM libfilename`

**Comment by rupor-github** [comment]
А зачем вы для flibusta формат указываете? Вот это: `--db-format 2017-05-3`?

Посмотрите [здесь](https://github.com/rupor-github/InpxCreator/blob/master/scripts/fb2_index.sh) - там вроде вполне полный пример...

**Comment by alexeystalker** [comment]
Да, если прямо с указанными параметрами запускать, то не падает. Спасибо!
