### ISSUE TITLE
ERROR: basic_string::_M_construct null not valid

### ISSUE THREAD

**Issue by rsarov** [rupor-github/InpxCreator#2]
Run
lib2inpx --ignore-dump-date --process **all** --strict db --db-name librusec --db-format 2011-11-06 --clean-authors E:\lib
or
lib2inpx --ignore-dump-date --process **usr** --strict db --db-name librusec --db-format 2011-11-06 --clean-authors E:\lib
and  not work **ERROR: basic_string::_M_construct null not valid** but
lib2inpx --ignore-dump-date --process **fb2** --strict db --db-name librusec --db-format 2011-11-06 --clean-authors E:\lib
OK 
help me

**Comment by rupor-github** [comment]
Я честно говоря не понял как проблема происходит - недостаточно информации, очень много возможных переменных. Давайте вы попробуете чуть-чуть подробнее. Неплохо было бы получить полный лог, а не только ошибку, знать какого числа был взят dump базы данных и т.д. Пока я могу сказать, что с 18 марта из дампов flibusta исчезла таблица avtoraliase - у меня, скажем вообще ничего не работает, возможно опять поменялся формат базы (или сломались скрипты)

**Comment by rupor-github** [comment]
Похоже у товарищей в librusec опять зачесался програмизм - начиная с февраля в базе появились книги с не инициализированным "keywords". Общим числом 365 - пока. Я починил, в версии 8.4  все должно работать.

**Comment by rsarov** [comment]
Оч, Оч, Очень хорошо, спасибо  и работает быстро. Я то по началу подумал а распарсю в  один проход, но когда понял, что надо к каждой книге цикл  запускать книга - автор и раньше никак не отскочить (может их много) впал в задумчивость (базы восстанавливать и т.д. и т.п), а оказалось что вы все уже сделали за что вам большое спб еще раз
