### ISSUE TITLE
Дополнение

### ISSUE THREAD

**Issue by rsarov** [rupor-github/InpxCreator#3]
Привет.
В базе есть  **md5**  хеши каждой книги, можно ли сделать, чтобы программа закидывала их в  **inp** в самое правое поле после последнего  **/x04.**
Объясню зачем мне это надо.  В  архивах (особенно usr) очень много непоняток и главная проблема  имена файлов. Имея md5 я смогу привести их к единому стандарту как в дампе и попутно избавиться от "не книг". Для этого правда придется определиться что же такое книга. Я определился все что угодно, но не делимое. То есть любой файл но один. Наборы **html** или **txt** файлов, связанные между собой это "не книги", а вот отдельный **chm** или **txt**  никак не зависимый от других вполне себе книга. Без крови конечно же не обойдется, но уж больно разрослись локальные копии библиотек причем качество содержимого не растет, а даже ноборот.

**Comment by rupor-github** [comment]
Прежде чем начинать думать вопрос: а как к этому отнесется MyHomeLib для которого собственно все это и создавалось?

**Comment by rsarov** [comment]
А какие здесь могут  вопросы  ничего же не меняется я представляю себе это типа  еще одного ключа типа --xx и  на выходе все тоже плюс md5. А блин самое главное я и не сказал. Мной написана утилита типа MyHomeLib, альтернатива если вам будет угодно я ее вчера только в паблик выложил
http://rutracker.org/forum/viewtopic.php?t=5377958 У нее несколько другая философия в частности не обновления бд а полная замена и скорость работы. Просто  у меня места не было все usr качать а потом когда тестировал выяснилась проблема с именами в usr надо формат бд менять, а это лишние поля, а с каждым лишним полем я теряю главное скорость. Я и так то обливаясь слезами дублировал в sqlite русские слова в верхний регистр.Поиск хоть и заявлен в sqlite как регистронезависимый, но только для енглиш. Вообщем это не срочно и если не охота возиться то и не надо. Все равно в основном fb2 все пользуются

**Comment by rupor-github** [comment]
Я посмотрю - и на md5, и на вашу программы, спасибо. По-поводу sqllite - когда я ковырялся с firmware для Sopy PRS там внутри все на sqllite. Ели я правильно помню его надо компилить с правильными языковыми опциями чтобы он поддерживал русский целиком и Sony добавляла custom extensions для подобной работы.

**Comment by rupor-github** [comment]
Версия 8.5 знает как произвести Inpx файл с md5
