### ISSUE TITLE
Win 7 x64 - отсутствует вывод в консоль

### ISSUE THREAD

**Issue by alzhur** [rupor-github/InpxCreator#4]
Сежескачанный релиз 8.5 (https://github.com/rupor-github/InpxCreator/releases/download/8.5/lib2inpx-win64.7z) при запуске с любыми параметрами не даёт никакого вывода в консоль с любым проверенным набором параметров, даже просто с --help
![console](https://cloud.githubusercontent.com/assets/26850616/24585935/b80a59de-17af-11e7-939a-1a0fe49faf6c.jpg)
Предыдущие версии сам не проверял, но натыкался на форумах на аналогичные жалобы на версию 6.1 или 6.2.

**Comment by rupor-github** [comment]
Это очень старая проблема, связанная с версией msvcrt.dll на Windows 7 и тем, как console обрабатывает UTF-8. Имеется несколько способов обойти проблему (использовать Visual Studio вместо gcc, построить mingw так, чтобы он использовал другой run-time, скажем msvcr110.dll и т.д.). К сожалению все эти способы весьма трудоемки и требуют отдельного билда для windows 7. Поскольку в Windows 10 все давно починено (и тот же код прекрасно работает под Linux) я этого делать не буду, жалко времени. Так как программа не интерактивная - тем, кто не хочет или не может переехать на Windows 10 предлагаются следующие workarounds:

1. Использовать redirect в файл: `lib2inpx >result.txt 2>&1` и смотреть результат из файла.
2. Использовать piping через работаюший pager (стандартный "more" на Window 7 не работает с UTF-8), например [отсюда](https://www.guysalias.tk/misc/less/): `lib2inpx --help | less`

![untitled](https://cloud.githubusercontent.com/assets/5368784/24590982/359a4f34-17c5-11e7-8013-758ae6e2ec48.jpg)
