### ISSUE TITLE
Flibusta - бардак с сериями в сгенерированном inpx

### ISSUE THREAD

**Issue by alzhur** [rupor-github/InpxCreator#5]
При генерации inpx по базе флибусты путаются авторские и издательские серии.
Такое впечатление, что программа находит все серии для книги, и, не разбирая их типа, берёт в работу какую-то одну, случайную.
Как результат - после загрузки получившегося файла в MyHomeLib, авторская серия книг может быть размазана по нескольким сериям: авторской, и одной или более издательским.
Возможная причина -  не учитываются какие-то нюансы актуального формата базы флибусты.

**Comment by rupor-github** [comment]
Мне кажется, что программа делает ровно то, что ее просят:

**--prefer-fb2 arg**
`Try to parse fb2 in archive to get information (default: ignore). "ignore" - ignore fb2 information, "merge" - always prefer book sequence info from fb2, "replace" - always use book sequence info from fb2`

В случае "ignore" - что есть в базе, то и будет в inpx. В случае "replace" - что было в fb2 будет в inpx, в случае "merge" - если в FB2 есть серия, она будет использована, исли нет - будет использовано то, что есть базе данных.  Если при этом серии размазываются КМК это проблема исходных данных, а не программы.

Если что-то работает не так, как заявлено - нужны конкретные примеры, я попробую исправить.

**Comment by alzhur** [comment]
Примеры из темы на форуме буктрекера:
http://flibusta.lib/b/480573  - в inpx попадает издательская серия
`Мзареулов,Константин,:sf_action:sf_space:sf:Экстремальные услугиФантастический боевик19948057314344594805730fb22017-04-01ru `


http://flibusta.lib/s/2683 - у части книг из серии в inpx попадает издательская серия, причём при работе по дампах от 1 марта и 1 апреля - у разных.
Например, 3-я книга серии:
```
lib.libbook.sql
(155412,1860560,'2009-06-28 12:14:17','Жемчужный орден','','ru','','fb2','UTF-8',2008,'0','2.0','MCat78',10571,'','19cb2b96fca5cf25bef74dde11bf4dd6','2017-04-01 18:40:05','4dace90a121e3cb2448c0d016651a876',0)
lib.libseq.sql
(155412,2683,3,1,0)
(155412,2682,0,101,1)
lib.libseqname.sql
(2683,'Невменяемый колдун')
(2682,'Фантастический боевик') 
```
в inpx сформированном по первомартовской базе - в серии "Невменяемый колдун", а в первоапрельском - в "Фантастический боевик".

**Comment by rupor-github** [comment]
Это в 8.6 исправлено - для flibusta серии будут сортироваться по типу, по умолчанию авторская серия (Type=0) имеет более высокий приоритет. Интересно было бы еще понять как flibusta использует поле Level...

**Comment by alzhur** [comment]
Насчёт Level есть такое предположение:
Поле используется для обозначения вложенных серий.
Для авторских серий значение равно уровню вложенности.
Для издательских серий - уровень+100.

**Comment by rupor-github** [comment]
Интересное предположение, хотя я не вполне понимаю зачем, но можно поискать подтверждения и подумать если это можно/нужно использовать
