### ISSUE TITLE
Query error (1146) Table 'librusec_20170425.libavtorname' doesn't exist

### ISSUE THREAD

**Issue by Challenger71** [rupor-github/InpxCreator#6]
Здравствуйте!
Помогите пожалуйста найти где проблема!
Решил перейти на новую версию lib2inpx 8,62 со старой 5,52 , 
Запускаю на Win10-Pro , проблемные файлы (libseq.sql и libbook.sql) - исправлены заранее, т.е. 
```
`sn` int(12)
и
  `Modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
```
соответственно

- построение базы из дампов, происходит без ошибок (вроде бы), далее отрабатывает --clean-authors
- а потом , при попытке обработать любой архив (неважно какой, новый или старый), пробовал с десяток, получаю такое:

```
> Archives processing - 1 file(s) [E:/Temp/BOOKs/]
> 
> Processing - "fb2-xxxxxx-xxxxxx.zip"
> 
> ***ERROR: Query error (1146) Table 'librusec_20170425.libavtorname' doesn't exist
> SELECT `FirstName`,`MiddleName`,`LastName` FROM libavtorname WHERE aid=8351;
```

aid=8351  - тут разные цифры, зависит от fb2-архива

Как это побороть? или Где мой косяк?
с уважением, Challenger71

**Comment by rupor-github** [comment]
Давайте по порядку, так как я вообще пока ничего не понимаю...

1. Дампы какой библиотеки (где их взять чтобы повторить вылет)?
2. Зачем нужно править дампы, что значит проблемные файлы?
3. Какая полная коммандная строка при запуске?

**Comment by Challenger71** [comment]
1. Дампы Либресека , тут: https://lib.rus.ec/sql/

2. - в дампе "libseq.sql" - заменяю соотв. строку на   

> `sn` int(12) NOT NULL

, иначе MyHomeLib не читает серий книг , т.е. вместо серии вида "х.00" , получаем на выходе целое число "Х" как было раньше.
- в дампе "libbook.sql" - заменяю соотв. строку на 

> `Modified` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',

 иначе вначале обработки самого дампа, вылет с сообщением о том что обнаружено "DEFAULT CURRENT_TIMESTAMP" в другом поле, и т.п.
с такими правками, моя старая версия (5,52), создет правильный inpx-файл без проблем.

3. комманда запуска:
`lib2inpx.exe --db-name=librusec --ignore-dump-date --process=fb2 --db-format=2011-11-06 --inpx-format=2.x --read-fb2=all --clean-authors --quick-fix --comment=comment_all.utf8 --inpx=.\inpx\librusec_local_fb2.inpx --archives="E:\BOOKs" .\SQL
`
Хотел, посмотреть как формируются серии с новым ключем --prefer-fb2=complement (т.к. с merge или replace - полная чехарда на выходе) , поэтому и пробую запустить новую версию.

4. - построение базы из дампов, происходит без ошибок (вроде бы), далее отрабатывает --clean-authors
- а потом , при попытке обработать любой архив (неважно какой, новый или старый), пробовал с десяток, получаю такое (Есть "result.txt" - это полный лог, но незнаю как загрузить сюда, потому скопирую сам текст:): 

> Detected MySQL dump date: none
> 
> Creating MYSQL database "librusec_20170425"
> 
> Importing - "libavtor.sql"            - done in 00:00:52
> Importing - "libavtors.sql"           - done in 00:00:55
> Importing - "libbook.sql"             - done in 00:05:03
> Importing - "libgenre.sql"            - done in 00:00:47
> Importing - "libgenremeta.sql"        - done in 00:00:00
> Importing - "libgenres.sql"           - done in 00:00:00
> Importing - "libmag.sql"              - done in 00:00:04
> Importing - "libmags.sql"             - done in 00:00:00
> Importing - "libpolka.sql"            - done in 00:01:02
> Importing - "libquality.sql"          - done in 00:00:05
> Importing - "librate.sql"             - done in 00:00:56
> Importing - "libseq.sql"              - done in 00:00:21
> Importing - "libseqs.sql"             - done in 00:00:07
> 
> Processing duplicate authors
>    De-duping author   202733 (   0) : Alisse--
>    De-duping author   134725 (   0) : denbr--
> *  De-duping author   187190 (   0) : Fidelia--
> *  De-duping author   187191 (   0) : Fidelia--
>    De-duping author   187194 (   0) : Redhat--`
> -******* ПРОПУСКАЮ, т.к. очень много строк "De-duping author"  **********
>    De-duping author   174915 (   0) : Гнатюк-Ярослав-
>    De-duping author   174917 (   0) : Гнатюк-Ярослав-
> 
> Archives processing - 4 file(s) [E:/BOOKs/]
> 
> Processing - "fb2-603000-605288.zip"  
> 
> ***ERROR: Query error (1146) Table 'librusec_20170425.libavtorname' doesn't exist
> SELECT `FirstName`,`MiddleName`,`LastName` FROM libavtorname WHERE aid=8351;

aid=8351 - тут разные цифры, зависит от номера fb2-архива , с версией 8,61 - то же самое

Как это побороть? или Где мой косяк? - Помогите пожалуйста найти где проблема!

**Comment by rupor-github** [comment]
1. Проблема с libavtorname - это мой bug, очень недавний, я его починил
2. Проблемы с изменением формата squence number в libruseq я убрал, редактировать dump не нужно, все и так будет работать.
3.  Проблему с timestamp мне ни воспроизвести ни понять не удалось - действительно, структура базы такова, что mysql предупреждает, что подобная инициализация timestamp устарела, но это warning, а не error и она ничему не мешает. Зачем нужно насиловать dump я так и не понял, если будут проблемы - открывайте отдельное issue, будем разбираться.

А так - забирайте новую версию.

**Comment by Challenger71** [comment]
**Большое Вам спасибо!**
завтра буду тестить, и по итогам здесь ещё напишу . Если всё ОК, то тоже напишу.
