### ISSUE TITLE
Дополнение

### ISSUE THREAD

**Issue by rsarov** [rupor-github/InpxCreator#7]
Привет.
Создание inpx для librusec.
В дампе **libbook.sql** последнее  поле №20 каждой книги ReplacedBy является признаком замены книги то есть если в нем 0 - книга не заменена, если не 0 то **bid** замены, можно ли сделать, чтобы программа закидывала это поле в inp в самое правое поле после последнего /x04. как вы уже это делали для md5.
Объясню зачем мне это надо.
Для создания базы "чистых книг" то есть без признака удаления(это уже есть) и без признака замены.
Я хочу включить lib2inpx.exe в состав libruks (просто добавив пользовательский интерфейс для работы с утилитой, чтобы любой мог при желании сделать inpx на свой вкус)

**Comment by rupor-github** [comment]
Версия 9.1 - если inpx-format=ruks и db-format=2017-05-31 программа выведет доплнительное поле после md5 содержащее значение ReplacedBy.  Хотя честно говоря мне все это кажется некоей лабудой: учитывая, что известно время добавления книги в базу и тот факт, что номера книг всегда монотонно возрастают, поле это совершенно казалось бы не нужно - мне не удалось увидеть ни одного не совпатающего title для замененных книг.

**Comment by rsarov** [comment]
Спасибо. Это некая декорация для пользователей, которые не понимают принципа wiki на котором построена либрусек ( например признак удаления не всегда означает, что есть такая же нормальная книга, замена, а там просто страничка сделана про запас, не адекватная замена тоже бывает, хотя в основном такая добавили обложку, картинки, просто страничка есть книги нет и наконец несоответствие содержания книга детская сказка, а открываешь руководство по эксплуатации пистолета стечкина, нечитаемый файл ладно хватит, а то посижу еще чего нибудь вспомню)
Вообщем ваши труды пригодятся тем кто не хочет видеть в базе  по несколько названий одной книги, еще раз спасибо.
Я наверное еще  к вам обращусь, есть мысль добавить к архивам либрусека все что есть на флибусте, но нет в либрусеке. Правда ка это сделать я пока не знаю.
