### ISSUE TITLE
Не вставляет комментарий из utf8-файла в inpx-файл для библиотеки librusec.

### ISSUE THREAD

**Issue by Challenger71** [rupor-github/InpxCreator#8]
Здравствуйте!
Новая версия 9.1 работает отлично с либрусеком, в смысле что видимых глюков не наблюдается.
Но, на днях случайно заметил (после переименования созданного inpx-файла в ZIP), что в комментарии самого файла(архива) пишет "librusec-2017-xx-xx", т.е. дата создания, хотя должно вставлять текст из моего файла comment_fb2.utf8 (ключ --comment=comment_fb2.utf8)
Раньше всегда так вставляло, до какой-то версии 8.6х точно, 
когда слетело (с какой версии) незнаю, т.к. только на днях заметил.
А в файле "collection.info", внутри inpx-а - всё правильно! тот же текст что и в comment_fb2.utf8

Не критично, но если не очень сложно, почините пожалуйста при выпуске новых версий.

Спасибо!

**Comment by rupor-github** [comment]
Эта функциональность была убрана (сознательно) во время выпуска 7.0, когда я начал готовить код программы к Linux. Дело в том, что zip с момента создания не специфицировал кодировку того, что будет лежать в zip file header. Разные программы, имеющие дело с архивами, ожидают разного представления данных и плохо понимали друг друга. Поэтому при создании комментариев (чтобы их можно было читать) использовалсась текущая code page на Windows (ANSI). Поддержать этo cross platform, так, чтобы скажем файлы созданные на Linux с рисскими комментариями надежно читались на Windows - или наоборот, я не смог и так как комментарии нигде и не для чего не используются - это было убрано. Для создания же файлов inpx и collection.info мы напрямую договорились с разработчиками MyHomeLib как все должно быть - и все так и есть. Так что чинить это я пожалуй пока не буду.

**Comment by Challenger71** [comment]
Всё понятно, **спасибо что разъяснили**.
Теперь, я так понимаю, важно лишь содержание файла collection.info, а на внутренний комментарй файлов inpx не обращать внимания вообще. Верно?
_Возможно, ещё кому-то пригодится информация по поводу комментария._

**Comment by rupor-github** [comment]
Комментарий никогда не использовался, более того, оригинальные удилиты для создания inpx его вообще не писали. Если мне не изменяет память, то я в самой первой версии lib2inpx подумал, что это хорошая идея. Оказалось, что хотел как лучше, а получилось как всегда :)
