### ISSUE TITLE
Ver.9.3 - Error Table mysql innodb_table_stats not found

### ISSUE THREAD

**Issue by Challenger71** [rupor-github/InpxCreator#9]
Здравствуйте!
Решил опробовать новую 9,3 версию. INPX - создаются правильно, MHL - обновляется из них также без проблем.
Сори, но опять надоедаю, с вероятно глупым вопросом:
При каждом запуске lib2inpx, в первой строке теперь всегда вылетает вот такая ошибка: **InnoDB: Error: Table "mysql"."innodb_table_stats" not found**
Число 1040, перед InnoDB, при каждом запуске другое показывает.
Дампы тут: https://lib.rus.ec/sql/
Скрин прицепил
![error table mysql innodb_table_stats not found](https://user-images.githubusercontent.com/28020305/27986337-a7dccd6e-6406-11e7-962f-c8cad4579edd.PNG)

- Возможно, на это попросту не обращать внимания? т.к. в итоге, всё отрабатывает корректно, и библиотека тоже обновляется без ошибок.

**Comment by rupor-github** [comment]
Да, можно игнорировать, можно создать конфигурацию для MySQL с выключенными persistent stats для InnoDB, а можно взять версию 9.4.

**Comment by Challenger71** [comment]
Спасибо!
Со следующим обновлением, буду с 9,4 создавать INPX
Как я понял, в новой версии, ничего не надо вручную выключать? В смысле вставлять параметр выключения persistent stats в CFG файл.

**Comment by rupor-github** [comment]
Нет, не надо. Или - да, не надо. Не знаю как правильно.
